# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: /research/
    weight: 20
  - name: People
    url: /people/
    weight: 30
  - name: Papers
    url: /publication/
    weight: 40
  - name: Software
    url: /software/
    weight: 50
  - name: Talks
    url: /talk/
    weight: 60
  - name: Teaching
    url: /courses/
    weight: 70
  - name: News
    url: /news/
    weight: 80
  - name: Join Us
    url: /join/
    weight: 90
  - name: "⚽ WC 2026"
    url: /wc2026/
    weight: 100
