#!/usr/bin/env python3
"""
Generate the Monte Carlo model's PRE-TOURNAMENT bracket and emit it as
static/wc2026/mc_bracket.js (window.MC_BRACKET). The leaderboard scores this
bracket client-side against the live `results` table, so the model appears as a
benchmark entry that updates as real results come in — no database writes needed.

The bracket is the model's single most-likely pre-tournament outcome, built from
the page's own pre-tournament data (no live results):
  - group winner / runner-up : GROUPS[g].proj (the pre-tournament projection)
  - third place              : stronger of the two non-projected teams (PRIOR_PROBS r32%)
  - 8 qualifying thirds       : highest pre-tournament r32% among the 12 thirds
  - R32 pairings             : official FIFA 495 third-place table
  - every knockout match      : the favourite advances (PRIOR_PROBS strength)

Output format mirrors how the site stores predictions, so the same scoring rules
apply:  grp1/grp2 {slot->team}, grpT ["G:Team"...], r32..final {slot->winner}.

RUN
  python scripts/generate_mc_bracket.py
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wc_combo495 import COMBO495, SLOT_ORDER_495  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "static" / "wc2026" / "index.html"
OUT_DIR = ROOT / "static" / "wc2026"

GROUP_IDX = {g: i for i, g in enumerate("ABCDEFGHIJKL")}
R32_FEEDERS = [
    ("W:E", "T:M74"), ("W:I", "T:M77"), ("R:A", "R:B"), ("W:F", "R:C"),
    ("R:K", "R:L"), ("W:H", "R:J"), ("W:D", "T:M81"), ("W:G", "T:M82"),
    ("W:C", "R:F"), ("R:E", "R:I"), ("W:A", "T:M79"), ("W:L", "T:M80"),
    ("W:J", "R:H"), ("R:D", "R:G"), ("W:B", "T:M85"), ("W:K", "T:M87"),
]


def parse_inputs():
    src = INDEX.read_text()
    gm = re.search(r"const GROUPS = \{(.*?)\n    \};", src, re.S).group(1)
    groups = {}
    for line in gm.strip().splitlines():
        m = re.match(r'\s*([A-L]):\{teams:\[(.*?)\],proj:\[(.*?)\]\}', line)
        if m:
            groups[m.group(1)] = {
                "teams": [t.strip().strip('"') for t in m.group(2).split(",")],
                "proj": [t.strip().strip('"') for t in m.group(3).split(",")],
            }
    pm = re.search(r"const PRIOR_PROBS=\{(.*?)\n    \};", src, re.S).group(1)
    prior = {}
    for m in re.finditer(
        r'"([^"]+)":\{champ:([\d.]+),r32:([\d.]+),r16:([\d.]+),qf:([\d.]+),sf:([\d.]+)\}', pm):
        prior[m.group(1)] = {k: float(v) for k, v in zip(
            ("champ", "r32", "r16", "qf", "sf"), m.groups()[1:])}
    return groups, prior


def strength(prior, t):
    p = prior.get(t, {})
    # Favourite ordering for a knockout match: weight deeper-round odds heavily.
    return (p.get("champ", 0) * 100 + p.get("sf", 0) * 10 + p.get("qf", 0) * 5
            + p.get("r16", 0) * 2 + p.get("r32", 0))


def load_corrected_prior():
    """If scripts/mc_prior.json exists (regenerated by the CORRECTED engine —
    FIFA 495 + tie-break, pre-tournament), use it so the model is judged on the
    same correct pathway as everyone else. Returns (prior, win, ru, third) or None."""
    f = Path(__file__).resolve().parent / "mc_prior.json"
    if not f.exists():
        return None
    d = json.loads(f.read_text())
    return d["prior"], d["groupWin"], d["groupRu"], d["groupThird"]


def main():
    groups, prior = parse_inputs()
    corrected = load_corrected_prior()
    if corrected:
        prior, win_modal, ru_modal, third_modal = corrected
        winners = dict(win_modal)
        runners = dict(ru_modal)
        print("Using CORRECTED pre-tournament prior (FIFA 495 + tie-break).")
    else:
        winners = {g: groups[g]["proj"][0] for g in groups}
        runners = {g: groups[g]["proj"][1] for g in groups}
        third_modal = None

    # Third place per group: the corrected engine's modal 3rd if available, else
    # the stronger of the two non-projected teams.
    thirds_all = []
    for g in groups:
        if third_modal and third_modal.get(g):
            third = third_modal[g]
        else:
            rest = [t for t in groups[g]["teams"] if t not in groups[g]["proj"]]
            third = max(rest, key=lambda t: strength(prior, t))
        thirds_all.append((g, third))
    # 8 best thirds by pre-tournament r32%.
    thirds_all.sort(key=lambda gt: -prior.get(gt[1], {}).get("r32", 0))
    thirds = sorted(thirds_all[:8], key=lambda gt: gt[0])

    key = "".join(g for g, _ in thirds)
    enc = COMBO495[key]
    third_by_group = dict(thirds)
    third_by_slot = {SLOT_ORDER_495[i]: third_by_group[enc[i]] for i in range(8)}

    def resolve(tok):
        kind, ref = tok.split(":")
        return {"W": winners, "R": runners}[kind][ref] if kind in "WR" else third_by_slot[ref]

    r32 = {i: (resolve(a), resolve(b)) for i, (a, b) in enumerate(R32_FEEDERS)}

    def play(matchups):
        winners_out, picks = {}, {}
        for idx, (a, b) in matchups.items():
            w = a if strength(prior, a) >= strength(prior, b) else b
            winners_out[idx], picks[idx] = w, w
        return winners_out, picks

    w32, p32 = play(r32)
    r16 = {i: (w32[2 * i], w32[2 * i + 1]) for i in range(8)}
    w16, p16 = play(r16)
    qf = {i: (w16[2 * i], w16[2 * i + 1]) for i in range(4)}
    wqf, pqf = play(qf)
    sf = {i: (wqf[2 * i], wqf[2 * i + 1]) for i in range(2)}
    wsf, psf = play(sf)
    fin = {0: (wsf[0], wsf[1])}
    wfin, pfin = play(fin)

    bracket = {
        "grp1": {str(GROUP_IDX[g]): winners[g] for g in groups},
        "grp2": {str(GROUP_IDX[g]): runners[g] for g in groups},
        "grpT": [f"{g}:{t}" for g, t in thirds],
        "r32": {str(k): v for k, v in p32.items()},
        "r16": {str(k): v for k, v in p16.items()},
        "qf": {str(k): v for k, v in pqf.items()},
        "sf": {str(k): v for k, v in psf.items()},
        "final": {"0": pfin[0]},
        "name": "Monte Carlo (pre-tournament)",
    }

    (OUT_DIR / "mc_bracket.json").write_text(json.dumps(bracket, indent=2, ensure_ascii=False))
    (OUT_DIR / "mc_bracket.js").write_text(
        "/* Pre-tournament Monte Carlo bracket — generated by scripts/generate_mc_bracket.py */\n"
        "window.MC_BRACKET=" + json.dumps(bracket, ensure_ascii=False) + ";\n"
    )
    print("Champion pick:", pfin[0])
    print("Final:", fin[0][0], "vs", fin[0][1])
    print("Thirds:", bracket["grpT"])
    print("Wrote static/wc2026/mc_bracket.js / .json")


if __name__ == "__main__":
    main()
